name: bitchat_flutter_plugin
description: Flutter plugin for bitchat protocol and Bluetooth mesh networking
version: 0.0.1

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Bluetooth and networking
  bluetooth_low_energy: ^6.0.2
  permission_handler: ^11.3.1
  
  # Encryption and crypto
  crypto: ^3.0.3
  pointycastle: ^3.7.3
  cryptography: ^2.7.0
  

  
  # Utilities
  uuid: ^4.3.3
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.10

# Platform-specific code
flutter:
  plugin:
    platforms: {} 